### ISSUE TITLE
NVIC_SetVector needed, even for Cortex M0 / M0+

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/cmsis-core#19]
Several Cortex M0 / M0+ based MCUs (e.g. Freescale KL* & ST STM32 L0) support relocation of vectors into RAM with NVIC VTOR.  

Currently, cmsis-core.c does not define NVIC_SetVector for any Cortex M0 or M0+.  

Why disable this feature for all Cortex M0 / M0+ ?!?!?!  

Please allow for NVIC_SetVector to be implemented for Cortex M0 / M0+ if they support it.  Perhaps move the definition of this function into the cmsis-core-<vendor> modules.

**Comment by 0xc0170** [comment]
There's a comment with an explanation https://github.com/ARMmbed/cmsis-core/blob/master/source/cmsis_nvic.c#L33, briefly, usually m0 have various vector reallocation implementations.

The PR adding this feature where you can find more details, https://github.com/ARMmbed/cmsis-core/pull/8.

@AlessandroA

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1161

**Comment by 0xc0170** [comment]
@maclobdell We don't have readme for this module, where we could add this information about setvector. I'll create a separate issue for creating readme, and will add there information to answer the questions above.

**Comment by maclobdell** [comment]
Hi, I understand that this is documented in a comment.  I also agree that a readme file would be good.  

However, I don't agree that "usually m0 have various vector reallocation implementations" is a good reason to disable the feature for all Cortex M0/M0+.

At least two major partners with Cortex M0/M0+ use NVIC VTOR registers for vector relocation (ST & Freescale), right?  So, I really recommend we do not cut off this feature completely!  :)

I think it is confusing to have NVIC_SetVector undefined based on the core.  If you don't want to move it back into the platform specific layer, then perhaps a warning could be inserted to let partners know that they need to define NVIC_SetVector themselves if they have a Cortex M0/M0+ with VTOR capability.

**Comment by 0xc0170** [comment]
#26 merged - more information about the solution there. I consider this resolved now
