### ISSUE TITLE
Does not work on CM0+

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/cmsis-core#6]
@0xc0170 @screamerbg @akselsm 
core_generic depends on a target to be 'like cortex_m0p' and tries to include core_cm0p.h, which doesn't exist.

The file that does exist is called core_cm0plus.h. Also, CThunk.h in mbed-drivers seems to rely on a definition of 'like cortex_m0plus', so I'm left wondering what the actual convention is here. You can't possibly expect to make a target define both M0P and M0PLUS... That would result in a define hell.

**Comment by 0xc0170** [comment]
Thanks for reporting, I am going to fix the include here and look at the correct definition, to fix also that. Will report back

**Comment by 0xc0170** [comment]
please define target as cortex-m0plus. I corrected it in this repository.
